# Services

services:

  # The main cli app
  cli:
    class:  \Lime\Cli\LimedocsCli


  # The logger
  logger:
    class:  \Lime\Logger\LoggerProxy
    factory_class:  \Lime\App
    factory_method: getLogger

  # Limedocs use doctrine/cache providers
  #
  # See the list here:
  #     - https://github.com/doctrine/cache/tree/master/lib/Doctrine/Common/Cache
  #
  #
  cache:
    class:        \Lime\Common\Cache
    arguments:    []

