# Services

services:

  # Limedocs use doctrine/cache providers
  #
  # See the list here:
  #     - https://github.com/doctrine/cache/tree/master/lib/Doctrine/Common/Cache
  #
  #
  cache:
    class:        \Lime\Common\Cache
    arguments:    []

